---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sonarqube.sonarqube.io
  resources:
  - sonarqubebackups
  - sonarqubebranchrules
  - sonarqubegroups
  - sonarqubeinstances
  - sonarqubeplugins
  - sonarqubeprojects
  - sonarqubequalitygates
  - sonarqubeusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sonarqube.sonarqube.io
  resources:
  - sonarqubebackups/finalizers
  - sonarqubebranchrules/finalizers
  - sonarqubegroups/finalizers
  - sonarqubeinstances/finalizers
  - sonarqubeplugins/finalizers
  - sonarqubeprojects/finalizers
  - sonarqubequalitygates/finalizers
  - sonarqubeusers/finalizers
  verbs:
  - update
- apiGroups:
  - sonarqube.sonarqube.io
  resources:
  - sonarqubebackups/status
  - sonarqubebranchrules/status
  - sonarqubegroups/status
  - sonarqubeinstances/status
  - sonarqubeplugins/status
  - sonarqubeprojects/status
  - sonarqubequalitygates/status
  - sonarqubeusers/status
  verbs:
  - get
  - patch
  - update
