## Append samples of your project ##
resources:
- sonarqube_v1alpha1_sonarqubeinstance.yaml
- sonarqube_v1alpha1_sonarqubeplugin.yaml
- sonarqube_v1alpha1_sonarqubeproject.yaml
- sonarqube_v1alpha1_sonarqubequalitygate.yaml
- sonarqube_v1alpha1_sonarqubeuser.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
