apiVersion: sonarqube.sonarqube.io/v1alpha1
kind: SonarQubeProject
metadata:
  name: my-project
  namespace: default
spec:
  instanceRef:
    name: my-sonarqube
  key: my-project-key
  name: My Project
  visibility: private
  mainBranch: main
  qualityGateRef: my-quality-gate
  ciToken:
    enabled: true
    secretName: my-project-ci-token
