apiVersion: sonarqube.sonarqube.io/v1alpha1
kind: SonarQubeInstance
metadata:
  labels:
    app.kubernetes.io/name: sonarqube-operator
    app.kubernetes.io/managed-by: kustomize
  name: sonarqubeinstance-sample
spec:
  # TODO(user): Add fields here
